# Generated by Django 2.0.6 on 2018-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_imageset_pinned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='zip_finished',
            field=models.BooleanField(default=True),
        ),
    ]
